server:
  port: 9090

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.118.131:8848 #注册中心地址
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #小写匹配服务service-id(默认大写)
      # 路由匹配规则
      routes:
        - id: nacos-provider-after-test
          uri: lb://nacos-provider-after-test
          predicates:
            - Path=/nacos-provider-after-test/**
          filters:
            - StripPrefix=1
        - id: nacos-provider-test
          uri: lb://nacos-provider-test
          predicates:
            - Path=/nacos-provider-test/**
          filters:
            - StripPrefix=1
