server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 10
      test-on-borrow: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
# redis 集群配置方式一
#  redis:
#    password: # Redis服务器连接密码（默认为空）
#    timeout: 3000ms # 连接超时时间
#    jedis:
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制）
#        max-active: 8
#        # 连接池中的最大空闲连接
#        max-idle: 8 # 连接池最大空闲连接数
#        # 连接池中的最小空闲连接
#        min-idle: 0 # 连接池最小空闲连接数
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制
#        # 超时关闭时间
#      shutdown-timeout: 100ms
#    cluster:
#      nodes:
#        - 192.168.118.131:6374
#        - 192.168.118.131:6375
#        - 192.168.118.131:6376
#        - 192.168.118.131:6377
#        - 192.168.118.131:6378
#        - 192.168.118.131:6379
  # redis 集群配置方式二
  redis:
    password:
    cluster:
      nodes: 192.168.118.131:6374,192.168.118.131:6375,192.168.118.131:6376,192.168.118.131:6377,192.168.118.131:6378,192.168.118.131:6379
      max-redirects: 6
      jedis:
        shutdown-timeout: 100ms
        pool:
          max-idle: 8
          max-active: 32
          min-idle: 8
          max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制

# Mybatis-plus
mybatis-plus:
  # 放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.onnoa.shop.demo.video.domain
  global-config:
    # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    # 字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
    field-strategy: 1
    # 驼峰下划线转换
    db-column-underline: true
    # 刷新mapper 调试神器
    refresh-mapper: true
    # 数据库大写下划线转换
    #capital-mode: true
    # 逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#七牛云配置
shop:
  qiniu:
    key:
      accessKey: 'JQWhEeHnkDGcofvpTCK4zlNdFL9wXUiDAAxhWcks'
      secretKey: '--q6xlmxFtWlBz7NwBV6G93YRL5N7ceUQT9SnDiH'
    bucket:
      name:
    oss:
      privateHost: 'http://qbsgsz0zg.bkt.clouddn.com'
      publicHost: 'http://qbsgsz0zg.bkt.clouddn.com'
      bucketName: 'onnoa-image'







