spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.118.131:8848 #注册中心地址
  redis:
    # Redis 服务器地址
    host: 192.168.118.131
    # Redis 数据库索引，默认为0
    database: 0
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接超时时间（毫秒）
    timeout: 3000ms
    # lettuce 和 jedis 的区别：
    # jedis ==》 如果在多线程环境下是非线程安全的，这个时候只有使用连接池，为每个Jedis实例增加物理连接
    # lettuce ==》 lettuce 在多线程环境下也是线程安全的，所以一个连接实例就可以满足多线程环境下
    # 的并发访问，当然一个实例不够的情况下也可以增加多个连接实例
    jedis: # 或 jedis SpringBoot默认是 lettuce
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 超时关闭时间
      shutdown-timeout: 100ms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.118.131:3306/sample_collections?characterEncoding=UTF8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 10
      test-on-borrow: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
